plot-doc/plot/scribblings/params.scrbl
plot-doc/plot/scribblings/renderer2d.scrbl
plot-doc/plot/scribblings/renderer3d.scrbl
plot-lib/plot/private/common/math.rkt
plot-lib/plot/private/common/parameters.rkt
plot-lib/plot/private/plot2d/point.rkt
plot-lib/plot/private/plot3d/point.rkt
plot-lib/plot/private/utils-and-no-gui.rkt
plot-lib/plot/utils.rkt

New optional arguments for `points` and `points3d`, and new parameters to match.
When `> 0`, parameters `x-jitter`, `y-jitter`, and `z-jitter` will add random noise to each point along the specified dimension.
New points lie within a rectangle with width `x-jitter`, height `y-jitter`, and depth `z-jitter` centered at each point's original location, but kept within the bounds for x-min, x-max, etc. given to `points` or `points3d`.
Inspired by R's [ggplot2](http://zevross.com/blog/2014/05/05/unhide-hidden-data-using-jitter-in-the-r-package-ggplot2/). I think this is a nice substitute for boxplots and violin plots.
Example:
```
#lang racket
(require plot)
(plot
(points (for/list ([_i (in-range 999)])
(list (* 10 (random)) 2))
#:alpha 0.4
#:y-jitter 0.5
#:sym 'fullcircle1
#:color "red") …
```

Jitter options & parameters (for plotting points)

---

plot-lib/plot/private/plot2d/rectangle.rkt
plot-test/plot/tests/plot2d-tests.rkt

The `#:samples` argument was implemented & documented, but not part of the type.
PR also adds a check for empty bins when making the `area-histogram`.
Empty bins are likely to happen `(- samples (length bin-bounds))` is small.
For example (using the `bin-samples` function from `plot-lib/plot/private/common/utils.rkt`):
```
(define bin-bounds '(0 9 10))
(define samples 4)
(define x* (linear-seq 0 10 samples
#:start? #f #:end? #f))
(displayln (bin-samples bin-bounds x*))
;; No samples fall in range [9, 10)
;; ((5/4 15/4 25/4 35/4) ())
```
Before this PR, `area-histogram` would raise a `division by zero` error

Add #:samples to type for area-histogram

---

plot-doc/plot/scribblings/renderer2d.scrbl

Instead of squares, use rectangles in the example for the `rectangles` 2d renderer.
This way, it's easier to tell how each `ivl` affects the plot.
Also replaces "list" & "vector" with "sequence", to match the newer type signature.

doc: use rectangles in  example

---

plot-doc/plot/scribblings/renderer2d.scrbl
plot-test/plot/tests/plot2d-tests.rkt

Just found myself wanting a partly-transparent vertical line.
`#:alpha` wasn't in the docs. Bummer. Let's see about adding it.
Lo and behold 'twas already implemented.
I thought about adding a test, but wasn't sure if I could just append to `plot2d-tests.rkt`

doc: add the #:alpha argument for hrule and vrule

---

plot-lib/plot/private/common/plot-device.rkt
plot-test/plot/tests/PRs/24.rkt

Fix a typo in a case statement clause, also add a test that plots all `known-point-symbols`
Closes #23

Fix typo, 'cirlce2' => 'circle2'

---

plot-doc/plot/scribblings/params.scrbl
plot-doc/plot/scribblings/renderer2d.scrbl
plot-lib/plot/no-gui.rkt
plot-lib/plot/private/common/parameters.rkt
plot-lib/plot/private/plot2d/point.rkt
plot-lib/plot/private/utils-and-no-gui.rkt

add a candlestick point plot that will show open, high, low, and close values commonly used for financial charts. include default parameters and documentation.
I apologize, but I have been unable to get raco to build, test, and display meaningful scribble documents for this PR. I can try to get that working, but if it's easier for someone else to kick off some continuous integration and see that things are okay, that would be helpful. I hope this contribution is welcome.

add a candlestick point plot

---

plot-gui-lib/plot/private/gui/plot3d.rkt
plot-lib/plot/private/no-gui/plot3d-utils.rkt

These three provided functions don't take any higher-order arguments and their
results are actually implemented in untyped code, so there should not be a
risk of segfaults, plus they check their first-order arguments. Additionally,
the result contracts have not been checked in past releases due to a bug in
contract generation, increasing confidence that this is safe.
Fixes racket/gui#86. Related to racket/typed-racket#599.
I hope to merge this for 6.12 to fix the regression noted in
racket/gui#86.

Provide plot3d interface unsafely to avoid excessive overhead.

---

plot-doc/plot/scribblings/contracts.scrbl
plot-doc/plot/scribblings/renderer2d.scrbl
plot-lib/plot/no-gui.rkt
plot-lib/plot/private/common/draw-attribs.rkt
plot-lib/plot/private/common/draw.rkt
plot-lib/plot/private/common/plot-device.rkt
plot-lib/plot/private/common/types.rkt
plot-lib/plot/private/plot2d/decoration.rkt
plot-lib/plot/private/plot2d/plot-area.rkt

The `point-pict` function adds a point to the graph and specifies a pict object to be displayed as the label.  This is similar to the `point-label` function, which can only show a string as the label.
`function-pict`, `inverse-pict`, `parametric-pict` and `polar-pict` are added similar to their *-label counterparts.
Sample code:
```racket
#lang racket
(require plot pict)
(define blue-fish (standard-fish 40 15 #:color "lightblue"))
(define red-fish (standard-fish 40 15 #:color "salmon"))
(define (f t) (vector (cos t) (sin t)))
(plot
(list (point-pict (vector 0 10) blue-fish #:anchor 'auto)
(point-pict (vector 0 -10) blue-fish #:anchor 'auto #:point-size 15)
(point-pict (vector 10 0) blue-fish #:anchor 'auto #:point-sym 'none)
(point-pict (vector -10 0) blue-fish #:anchor 'auto #:point-sym …
```

 Add `point-pict` 2d renderer, similar to `point-label`

---

plot-doc/plot/scribblings/renderer2d.scrbl
plot-doc/plot/scribblings/utils.scrbl
plot-lib/plot/private/plot2d/rectangle.rkt

When #f is specified to one of the interval bounds of the `rectangles`
renderer, the rectangle will extend to the edge of the plot area in the
direction of that bound.  Example:
```racket
#lang racket
(require plot)
(plot (rectangles (list (vector (ivl 2 3) (ivl #f #f))
(vector (ivl #f #f) (ivl 2 3))
;; Vertical extent from 0 to the top
(vector (ivl 5 6) (ivl 0 #f)))
#:line-style 'transparent
#:alpha 0.5)
#:x-min -10 #:x-max 10
#:y-min -10 #:y-max 10)
```
Implementation note: the rectangles renderer code used to compute the bounds
of the plot based on the bounds of the rectangles, this code is unnecessary
and complicates the case where the intervals are open-ended.  It was removed.

Extend `rectangles` renderer to accept open intervals

---

plot-test/plot/tests/plot2d-tests.rkt

Add tests from #33 and #34 to the repo.
@alex-hhh I made the second test (from #34) a little simpler because the test from #33 already plots 2 `'none` points. Let me know if you think we should make other changes, or add other tests.

test: add tests for 'auto, point-pict, etc

---

plot-doc/plot/scribblings/params.scrbl
plot-lib/plot/private/common/parameter-groups.rkt
plot-lib/plot/private/common/parameters.rkt
plot-lib/plot/private/plot2d/plot-area.rkt
plot-lib/plot/private/plot3d/plot-area.rkt
plot-lib/plot/private/utils-and-no-gui.rkt

This uses a different approach to showing ticks but hiding labels using feedback from @bennn and @alex-hhh on PR #41 
This was tested with the following code:
```
#lang racket
(require plot)
(parameterize ([plot-width    150]
[plot-height   150]
[plot-x-label  #f]
[plot-y-label  #f]
[plot-y-tick-labels? #f]
[plot-y-far-tick-labels? #t])
(plot (function sin (- pi) pi)))
```
This will produce:
I suppose some documentation will be nice here even though this seems much more straight forward.

add new params to control tick labels

---

plot-gui-lib/plot/private/gui/plot2d.rkt
plot-gui-lib/plot/private/gui/plot3d.rkt

`plot-frame` and `plot3d-frame` delays the creation of the plot snip object until the size of the canvas is known.  This means that the snip creation code is executed outside any `parameterize` scope and the values of any plot parameters (like `plot-decorations?`) would be ignored unless they are saved using `plot-parameters` and restored using `parameterize/group`
The fix is based on a problem reported here: https://groups.google.com/forum/#!topic/racket-users/ta-245wAYco
The issue was introduced when #39 was fixed, since at that time the plot snip was no longer created withing the scope of the `parameterize` call.
Here is some example code to test this (previously the two plots would have decorations, even though `plot-decorations?` is `#f):
```racket
#lang racket
(require plot) …
```

Capture plot parameters in plot-frame and plot3d-frame

---

plot-gui-lib/plot/private/gui/plot2d.rkt
plot-gui-lib/plot/private/gui/plot3d.rkt
plot-lib/plot/private/common/draw.rkt
plot-lib/plot/private/no-gui/plot2d.rkt
plot-lib/plot/private/no-gui/plot3d.rkt

The 2D and 3D plot commands from the "no-gui" library have been updated to use
`make-bitmap`, while the corresponding commands from the GUI library have been
now use `make-platform-bitmap`.
`make-platform-bitmap` will create a bitmap optimized for being displayed on
the screen, with the correct backing scale for the monitor -- the
`draw-bitmap/supersampling` always used a backing scale of 2 which resulted in
blurred text for non-HiDPI screens, also Windows uses a backing scale of 1.5
by default on HiDPI displays.
The non-gui plot commands were already using `make-bitmap` via a call to
`draw-bitmap` but `draw-bitmap` and `draw-bitmap/supersampling` have been
removed from "draw.rkt", as they were no longer used, and they were not
providing much abstraction anyway -- also …

Use platform specific bitmaps for rendering plots, where applicable

---

plot-doc/plot/scribblings/common.rkt
plot-doc/plot/scribblings/params.scrbl
plot-doc/plot/scribblings/utils.scrbl
plot-gui-lib/plot/private/gui/snip.rkt
plot-gui-lib/plot/private/gui/snip2d.rkt
plot-lib/plot/private/common/color-map.rkt
plot-lib/plot/private/common/draw-attribs.rkt
plot-lib/plot/private/common/parameter-groups.rkt
plot-lib/plot/private/common/parameters.rkt
plot-lib/plot/private/common/plot-device.rkt
plot-lib/plot/private/common/types.rkt
plot-lib/plot/private/plot3d/plot-area.rkt
plot-lib/plot/private/utils-and-no-gui.rkt
plot-lib/plot/utils.rkt

Plot renderers have a `#:color` argument which specifies the color to use for drawing, this can be a `color%` object, a RGB triplet, or an integer representing an index into a color palette.  This commit introduces a mechanism to select which color palette (called a color map) to use when integers are used for the `#:color` argument of the renderers.
```racket
(require plot)
(parameterize ([plot-pen-color-map 'set1]
[line-width 3])
(plot (list (function sin -5 5 #:color 0)
(function cos -5 5 #:color 1))))
```
The following new API functions are introduced and updated:
* `plot-pen-color-map` and `plot-brush-color-map` are new parameters which specify the name of a color map to use for the `#:color` argument of renderer functions.
* the `->pen-color` and `->brush-color` functions have been …

Add color map support for selecting colors for renderers

---

plot-doc/plot/scribblings/common.rkt

Requiring and initializing the GUI while building the documentation fails the
build.  The code to generate the color map picture only requires plot/no-gui
functions anyway.
As per discussion at https://github.com/racket/plot/commit/0e30a09f7499fb8349759fbf714b070d9255e3b4#commitcomment-33013748

use plot/no-gui instead of plot while rendering the scribble documentation

---

plot-doc/plot/scribblings/renderer3d.scrbl
plot-lib/plot/no-gui.rkt
plot-lib/plot/private/plot3d/param-surf.rkt

Adds a 3d renderer for paramteric surfaces
this is faster than the trick used for polar3d, where an isosurface is used, since the right values for the polygons can be directly computed
also exposes a renderer for polygons, similar to lines3d

Parametric surface3d

---

plot-doc/plot/scribblings/renderer3d.scrbl
plot-lib/plot/private/plot3d/isosurface.rkt

This addresses issue #48 
to add my 2cts to the discussion:
latitude and longitude are used for navigation on a/our globe
latitude is from pole to pole: ie from 90°South to 90°North,
Longitude is from 180°West to 180°East
so latitude conforms with the (- (/ pi 2)) to (/ pi 2) and longitude goes from (- pi) to pi (or alternatively from 0 to (* 2 pi))
For polar coordinates you have one angle going trough 360° and one going trough 180°
in the implementation the first angle (theta) is going trough 360° and the second trough 180°
This is how it is usually done, with the understanding that the 360° usually goes around the equator (here hardwired to the xy-plane) and the second angle from pole to pole
The mix up in my opinion is because in math you usually specify first the 360° angle, then the …

match use of latitude and longitude, and their domain

---

plot-doc/plot/scribblings/contracts.scrbl
plot-doc/plot/scribblings/plotting.scrbl
plot-gui-lib/plot/private/gui/plot2d.rkt
plot-gui-lib/plot/private/gui/plot3d.rkt
plot-lib/plot/private/common/contract.rkt
plot-test/plot/tests/PRs/plot-unsafe-provide.rkt

This PR adds regression tests for f53d103d37827ea83b41015da59fcd519a9345e0 , to check that the plot3d functions don't segfault on bad arguments.
While testing I realized I made a mistake yesterday (#27) --- plot's parameters are **not** always guarded with a contract. The parameters **do** seem safe against segfaults. But a bad value can give a bad error message, so this PR explicitly checks all keyword arguments to plot3d functions.
Also adds a `plot-file-format/c` contract. (Not necessary, but I think it's a good idea.)
(cc @stamourv I am not suggesting we merge this pull request into the release)

plot3d regression tests

---

plot-doc/plot/scribblings/ticks.scrbl
plot-lib/plot/private/common/ticks.rkt

The idea is to be able to get an scale like
8000    9000    10000    11000
instead of
8000    9000     10^5    11000
using 
(plot-x-ticks (linear-ticks #:scientific? #f))
Also, fix a few typos in the docs.

Add #:scientific? option to linear-ticks-format and linear-ticks

---

.github/workflows/ci.yml

This sets up a CI build for the plot package, scheduled to run for pushes and pull requests.  Currently it only runs for Racket version 7.7 and it does not run the tests.  Tests need are currently run manually and their output visually inspected.
It is inspired by the web-server CI build, but uses a different strategy for the build:
* minimal racket is installed
* a package catalog is setup for the packages in the plot repository
* this package catalog is added to the default racket catalogs
* the plot package is installed -- this will fetch packages form the local file system and build them, and will fetch all dependencies from the main racket catalog.
NOTE: there are several commits in this branch, as I was experimenting with different approaches, but I will squash the commits when …

Setup CI for the plot package

---

plot-doc/plot/scribblings/renderer2d.scrbl
plot-lib/info.rkt
plot-lib/plot/private/plot2d/point.rkt

This makes it possible to add horizontal error bars to a horizontal histogram.

Add #:invert? option to error-bars

---

plot-gui-lib/plot/private/gui/plot3d.rkt
plot-lib/plot/private/no-gui/plot2d-utils.rkt
plot-lib/plot/private/no-gui/plot3d-utils.rkt
plot-lib/plot/private/plot2d/arrows.rkt
plot-lib/plot/private/plot2d/color-field.rkt
plot-lib/plot/private/plot2d/contour.rkt
plot-lib/plot/private/plot2d/decoration.rkt
plot-lib/plot/private/plot2d/interval.rkt
plot-lib/plot/private/plot2d/line.rkt
plot-lib/plot/private/plot2d/point.rkt
plot-lib/plot/private/plot2d/rectangle.rkt
plot-lib/plot/private/plot2d/renderer.rkt
plot-lib/plot/private/plot3d/arrows.rkt
plot-lib/plot/private/plot3d/contour.rkt
plot-lib/plot/private/plot3d/decoration.rkt
plot-lib/plot/private/plot3d/isosurface.rkt
plot-lib/plot/private/plot3d/line.rkt
plot-lib/plot/private/plot3d/param-surf.rkt
plot-lib/plot/private/plot3d/point.rkt
plot-lib/plot/private/plot3d/rectangle.rkt
plot-lib/plot/private/plot3d/renderer.rkt
plot-lib/plot/private/plot3d/surface.rkt
plot-lib/plot/private/utils-and-no-gui.rkt

PR to begin solving #49 
This is a first attempt to separate legend and function calculation (2D)
The nastiest change is for contour and contour-intervals. The legend(label) and function calculation are quite interwoven for these procedures.
With this change it should be possible to get the legend entries at any point, provided the bounds for the plot area are known (necessary for contour/-intervals). 
For contour/-intervals it uses internal state to prevent calculating the function twice.

[legend pt1] legend outside plot area

---

plot-compat/plot/private/compat.rkt
plot-gui-lib/plot/private/gui/plot2d.rkt
plot-gui-lib/plot/private/gui/plot3d.rkt
plot-lib/plot/private/common/contract.rkt
plot-lib/plot/private/common/parameter-groups.rkt
plot-lib/plot/private/common/parameters.rkt
plot-lib/plot/private/common/plot-device.rkt
plot-lib/plot/private/common/types.rkt
plot-lib/plot/private/no-gui/plot2d-untyped.rkt
plot-lib/plot/private/no-gui/plot2d-utils.rkt
plot-lib/plot/private/no-gui/plot2d.rkt
plot-lib/plot/private/no-gui/plot3d-untyped.rkt
plot-lib/plot/private/no-gui/plot3d-utils.rkt
plot-lib/plot/private/no-gui/plot3d.rkt
plot-lib/plot/private/plot2d/plot-area.rkt
plot-lib/plot/private/plot3d/plot-area.rkt
plot-lib/plot/private/utils-and-no-gui.rkt

This build on #70 and #71 in order to implement #49.
Although all test pass, a little improvement can be made (changing 3 test cases), see [plot2d-utils#L73](https://github.com/racket/plot/blob/939390c7b3d5a858d7f1c5af2b246211bdbff83d/plot-lib/plot/private/no-gui/plot2d-utils.rkt#L73) and [plot3d-utils#L83](https://github.com/racket/plot/blob/939390c7b3d5a858d7f1c5af2b246211bdbff83d/plot-lib/plot/private/no-gui/plot3d-utils.rkt#L83)

[Legend pt3] Make legend available to area at start

---

plot-lib/plot/private/common/contract.rkt
plot-lib/plot/private/common/plot-device.rkt
plot-lib/plot/private/common/types.rkt
plot-lib/plot/private/plot2d/plot-area.rkt
plot-lib/plot/private/plot3d/plot-area.rkt

This PR builds on the previous (#70 #71 #72) to implement #49 
With this, space is reserved for drawing the legend outside of the plot area.
When the legend anchor is a corner (eg top-left etc.) the reserved space (horizontal or vertical) is based on the width/height of the legend. It tries to maximize the space for the plot area.
the fixpoint margin calculation was broken -- edit: see #75 
Also the margin calculation for pict titles in the 3d version was not updated -- edit: see #76 
---
```
(require plot pict)
(plot3d (list (surface3d (λ (x y) 1) 0 1 0 1 #:label "v" #:color 'blue)
(surface3d (λ (x y) 2) 0 1 0 1 #:label "x"))
#:legend-anchor '(outside right) #:title (text "a long title" null 12 1))
```

[legend pt5] Reserve space for outside legend

---

plot-doc/plot/scribblings/contracts.scrbl
plot-doc/plot/scribblings/params.scrbl
plot-doc/plot/scribblings/plotting.scrbl

Documentation update for PRs for #49

legend: update documentation

---

.github/workflows/ci.yml

This likely also fixes the CI issue from #86 (...somehow). Looking through the logs of the CI build:
```
Resolved "plot" via file:///home/runner/work/plot/plot/catalog
00: Resolved "plot-lib" via file:///home/runner/work/plot/plot/catalog
00: Resolved "plot-gui-lib" via file:///home/runner/work/plot/plot/catalog
Resolved "plot-doc" via file:///home/runner/work/plot/plot/catalog
```

make CI build from the repository and not from the catalog

---

plot-gui-lib/plot/private/gui/lazy-snip-typed.rkt
plot-gui-lib/plot/private/gui/lazy-snip-types.rkt
plot-gui-lib/plot/private/gui/plot2d.rkt
plot-gui-lib/plot/private/gui/plot3d.rkt
plot-gui-lib/plot/private/gui/snip2d.rkt
plot-gui-lib/plot/private/gui/snip3d.rkt
plot-lib/plot/private/common/contract.rkt
plot-lib/plot/private/common/plotmetrics.rkt
plot-lib/plot/private/common/types.rkt
plot-lib/plot/private/no-gui/evil-types.rkt
plot-lib/plot/private/no-gui/plot-bitmap.rkt
plot-lib/plot/private/no-gui/plot-pict.rkt
plot-lib/plot/private/no-gui/plot2d-untyped.rkt
plot-lib/plot/private/no-gui/plot2d.rkt
plot-lib/plot/private/no-gui/plot3d-untyped.rkt
plot-lib/plot/private/no-gui/plot3d.rkt
plot-lib/plot/private/plot2d/plot-area.rkt
plot-lib/plot/private/plot3d/plot-area.rkt
plot-lib/plot/private/utils-and-no-gui.rkt
plot-test/plot/tests/PRs/90.rkt

Possible implementation for getting plot-metrics from plots. see #83 
- `get-plot-boundaries`: `(-> (Vectorof (Vector Real Real))`  - give min/max x y (z) values
- `plot->dc`: `(-> (Vecorof Real) (Vectorof Real))` - translate plot x y (z) coordinates to dc x y coordinates
- This changes the return type for `plot/dc`, `plot-bitmap`, `plot-snip`, `plot-pict`
- typed-untyped interaction: Except for `plot-pict` the return types are new objects for which no interface or class is defined. There will be no straighforward way to check if the returned objects implement `Plot-Metrics<%>`

Plotmetrics

---

plot-doc/plot/scribblings/common.rkt
plot-doc/plot/scribblings/plotting.scrbl
plot-doc/plot/scribblings/utils.scrbl
plot-lib/plot/private/common/plotmetrics.rkt
plot-lib/plot/private/utils-and-no-gui.rkt
plot-lib/plot/utils.rkt
plot-test/plot/tests/PRs/90.rkt

Pull request #90 implements the plot-metrics interface, a mechanism that allows the user to determine the location of elements on the plot image itself, so plots can be further decorated, it is based on a request in issue #83.  While this functionality has been available for a while now, it was not documented.    This PR adds documentation to this interface, so potential users can discover the functionality and use it.
The `plot-metrics<%>` interface itself is not provided by the plot package, and while the functionality is accessible (e.g. calling plot-metrics methods), the user cannot test if a returned image implements this interface (see example below).  Unfortunately, this means that the scribble documentation is incorrectly linked...
```racket
#lang racket
(require plot plot/utils) …
```

Document the plot-metrics interface

---

plot-lib/plot/bitmap.rkt
plot-lib/plot/no-gui.rkt
plot-lib/plot/private/no-gui/plot2d-untyped.rkt

Remove extra defines from untyped reprovide modules. These aren't
needed for safety, and I don't think they help much with error
messages & keeping ids distinct either.
(After removing, the `define-typed/untyped-id` in plot work as-is
for Transient. If we kept the defines, transient would need new
identifiers.)

remove 'untyped-' redirects

---

plot-doc/plot/scribblings/ticks.scrbl
plot-lib/plot/private/common/ticks.rkt

Add a check that the ticks format function returns the same number of labels as input pre-tick elements.  Also updated the documentation to better explain what the function needs to return.

Clarify expectations for ticks-format function (#113)

---

plot-doc/plot/scribblings/ticks.scrbl

The old way, `@racket[format]`, links to the `racket/base` function.

doc: render ticks  as metavar, not link

---

plot-doc/plot/scribblings/utils.scrbl

these have been available but undocumented for years
- - -
I keep rediscovering them by requiring `plot/utils` and a `min*` / `max*` that expect lists. Adding this entry to the docs will make it easier to learn that `plot/utils` is the exporter.

doc: defproc for min*, max*
